type SeedWord = {
  word: string;
  word_form: string;
  ipa: string;
  meaning: string;
  example: string;
  sort_order: number;
};

export type SeedSet = {
  set_name: string;
  words: SeedWord[];
};

const TEST1: SeedWord[] = [
  { word: 'take place',       word_form: 'verb phrase',  ipa: '/teɪk pleɪs/',              meaning: 'diễn ra',                        example: 'The meeting will take place in the main conference room.', sort_order: 1  },
  { word: 'attendee',         word_form: 'noun',          ipa: '/ˌæt.enˈdiː/',              meaning: 'người tham dự',                  example: 'All attendees must sign in at the front desk.', sort_order: 2  },
  { word: 'antique',          word_form: 'noun / adj',    ipa: '/ænˈtiːk/',                 meaning: 'đồ cổ',                          example: 'The hotel lobby is decorated with antique furniture.', sort_order: 3  },
  { word: 'organization',     word_form: 'noun',          ipa: '/ˌɔːr.gən.aɪˈzeɪ.ʃən/',    meaning: 'tổ chức',                        example: 'She works for a nonprofit organization.', sort_order: 4  },
  { word: 'suspicious',       word_form: 'adjective',     ipa: '/səˈspɪʃ.əs/',              meaning: 'đáng ngờ',                       example: 'The manager found the report suspicious.', sort_order: 5  },
  { word: 'vary',             word_form: 'verb',          ipa: '/ˈver.i/',                  meaning: 'thay đổi, khác nhau',            example: 'Prices may vary depending on the season.', sort_order: 6  },
  { word: 'inventory',        word_form: 'noun',          ipa: '/ˈɪn.vən.tɔːr.i/',          meaning: 'hàng tồn kho',                   example: 'The store checks its inventory every month.', sort_order: 7  },
  { word: 'expand',           word_form: 'verb',          ipa: '/ɪkˈspænd/',                meaning: 'mở rộng',                        example: 'The company plans to expand its business overseas.', sort_order: 8  },
  { word: 'solicit',          word_form: 'verb',          ipa: '/səˈlɪs.ɪt/',               meaning: 'yêu cầu, kêu gọi',               example: 'The company solicited feedback from customers.', sort_order: 9  },
  { word: 'intend',           word_form: 'verb',          ipa: '/ɪnˈtend/',                 meaning: 'có ý định',                      example: 'We intend to complete the project by June.', sort_order: 10 },
  { word: 'prevent',          word_form: 'verb',          ipa: '/prɪˈvent/',                meaning: 'ngăn chặn',                      example: 'This software helps prevent data loss.', sort_order: 11 },
  { word: 'aim',              word_form: 'verb / noun',   ipa: '/eɪm/',                     meaning: 'mục tiêu, nhắm đến',             example: 'The campaign aims to attract new clients.', sort_order: 12 },
  { word: 'qualified',        word_form: 'adjective',     ipa: '/ˈkwɑː.lə.faɪd/',           meaning: 'đủ trình độ',                    example: 'Only qualified applicants will be contacted.', sort_order: 13 },
  { word: 'resident',         word_form: 'noun',          ipa: '/ˈrez.ɪ.dənt/',             meaning: 'cư dân',                         example: 'Local residents attended the community meeting.', sort_order: 14 },
  { word: 'agreement',        word_form: 'noun',          ipa: '/əˈɡriː.mənt/',             meaning: 'hợp đồng, thỏa thuận',           example: 'Both sides signed the agreement yesterday.', sort_order: 15 },
  { word: 'opposition',       word_form: 'noun',          ipa: '/ˌɑː.pəˈzɪʃ.ən/',           meaning: 'sự phản đối',                    example: 'The proposal faced strong opposition.', sort_order: 16 },
  { word: 'extensive',        word_form: 'adjective',     ipa: '/ɪkˈsten.sɪv/',             meaning: 'rộng rãi, mở rộng',              example: 'The company conducted extensive market research.', sort_order: 17 },
  { word: 'guarantee',        word_form: 'verb / noun',   ipa: '/ˌɡær.ənˈtiː/',             meaning: 'bảo đảm',                        example: 'The product comes with a one-year guarantee.', sort_order: 18 },
  { word: 'supplier',         word_form: 'noun',          ipa: '/səˈplaɪ.ər/',              meaning: 'nhà cung cấp',                   example: 'We contacted a new supplier for office equipment.', sort_order: 19 },
  { word: 'landscaping',      word_form: 'noun',          ipa: '/ˈlænd.skeɪ.pɪŋ/',          meaning: 'thiết kế cảnh quan',             example: 'The company hired a firm for garden landscaping.', sort_order: 20 },
  { word: 'suggestion',       word_form: 'noun',          ipa: '/səˈdʒes.tʃən/',            meaning: 'đề xuất',                        example: 'We welcome any suggestions to improve customer service.', sort_order: 21 },
  { word: 'expertise',        word_form: 'noun',          ipa: '/ˌek.spɜːrˈtiːz/',          meaning: 'chuyên môn',                     example: 'She has expertise in financial reporting.', sort_order: 22 },
  { word: 'competitor',       word_form: 'noun',          ipa: '/kəmˈpet.ɪ.tər/',           meaning: 'đối thủ cạnh tranh',             example: 'The company is facing strong competitors in the market.', sort_order: 23 },
  { word: 'anniversary',      word_form: 'noun',          ipa: '/ˌæn.ɪˈvɜːr.sər.i/',        meaning: 'kỷ niệm',                        example: 'The firm celebrated its 10th anniversary last week.', sort_order: 24 },
  { word: 'dedication',       word_form: 'noun',          ipa: '/ˌded.ɪˈkeɪ.ʃən/',          meaning: 'sự cống hiến',                   example: 'Her dedication to work impressed the manager.', sort_order: 25 },
  { word: 'loyalty',          word_form: 'noun',          ipa: '/ˈlɔɪ.əl.ti/',              meaning: 'sự trung thành',                 example: 'Customer loyalty is important for long-term success.', sort_order: 26 },
  { word: 'contribute',       word_form: 'verb',          ipa: '/kənˈtrɪb.juːt/',           meaning: 'đóng góp',                       example: 'All staff are encouraged to contribute ideas.', sort_order: 27 },
  { word: 'gratitude',        word_form: 'noun',          ipa: '/ˈɡræt.ɪ.tuːd/',            meaning: 'lòng biết ơn',                   example: 'The director expressed his gratitude to the team.', sort_order: 28 },
  { word: 'refine',           word_form: 'verb',          ipa: '/rɪˈfaɪn/',                 meaning: 'cải tiến',                       example: 'The design was refined after customer feedback.', sort_order: 29 },
  { word: 'spacious',         word_form: 'adjective',     ipa: '/ˈspeɪ.ʃəs/',               meaning: 'rộng rãi',                       example: 'The new office is bright and spacious.', sort_order: 30 },
  { word: 'go through',       word_form: 'phrasal verb',  ipa: '/ɡoʊ θruː/',                meaning: 'trải qua, xem xét',              example: 'Please go through the report carefully.', sort_order: 31 },
  { word: 'various',          word_form: 'adjective',     ipa: '/ˈver.i.əs/',               meaning: 'đa dạng',                        example: 'The seminar covers various business topics.', sort_order: 32 },
  { word: 'secure',           word_form: 'verb / adj',    ipa: '/sɪˈkjʊr/',                 meaning: 'đảm bảo; an toàn',               example: 'The company hopes to secure more clients.', sort_order: 33 },
  { word: 'remove',           word_form: 'verb',          ipa: '/rɪˈmuːv/',                 meaning: 'loại bỏ',                        example: 'Please remove outdated files from the system.', sort_order: 34 },
  { word: 'previous',         word_form: 'adjective',     ipa: '/ˈpriː.vi.əs/',             meaning: 'trước đó',                       example: 'Please refer to the previous email.', sort_order: 35 },
  { word: 'cooperation',      word_form: 'noun',          ipa: '/koʊˌɑː.pəˈreɪ.ʃən/',       meaning: 'sự hợp tác',                     example: 'Thank you for your cooperation.', sort_order: 36 },
  { word: 'upcoming',         word_form: 'adjective',     ipa: '/ˈʌpˌkʌm.ɪŋ/',             meaning: 'sắp tới',                        example: 'Details will be shared in the upcoming meeting.', sort_order: 37 },
  { word: 'charge',           word_form: 'verb / noun',   ipa: '/tʃɑːrdʒ/',                 meaning: 'tính phí; phí',                  example: 'The hotel does not charge extra for breakfast.', sort_order: 38 },
  { word: 'assign',           word_form: 'verb',          ipa: '/əˈsaɪn/',                  meaning: 'phân công',                      example: 'The manager will assign tasks tomorrow.', sort_order: 39 },
  { word: 'administrator',    word_form: 'noun',          ipa: '/ədˈmɪn.ɪ.streɪ.tər/',      meaning: 'quản trị viên',                  example: 'Please contact the system administrator for help.', sort_order: 40 },
  { word: 'new hire',         word_form: 'noun',          ipa: '/nuː haɪr/',                meaning: 'nhân viên mới',                  example: 'The new hires will attend orientation on Monday.', sort_order: 41 },
  { word: 'promote',          word_form: 'verb',          ipa: '/prəˈmoʊt/',                meaning: 'thăng chức; quảng bá',           example: 'The company plans to promote the new service.', sort_order: 42 },
  { word: 'advertise',        word_form: 'verb',          ipa: '/ˈæd.vər.taɪz/',            meaning: 'quảng cáo',                      example: 'The product was advertised online.', sort_order: 43 },
  { word: 'coordinator',      word_form: 'noun',          ipa: '/koʊˈɔːr.də.neɪ.tər/',      meaning: 'người điều phối',                example: 'Please contact the event coordinator for details.', sort_order: 44 },
  { word: 'telescope',        word_form: 'noun',          ipa: '/ˈtel.ɪ.skoʊp/',            meaning: 'kính thiên văn',                 example: 'The museum displayed an old telescope.', sort_order: 45 },
  { word: 'revise',           word_form: 'verb',          ipa: '/rɪˈvaɪz/',                 meaning: 'sửa đổi',                        example: 'The schedule has been revised.', sort_order: 46 },
  { word: 'representative',   word_form: 'noun',          ipa: '/ˌrep.rɪˈzen.tə.tɪv/',      meaning: 'đại diện',                       example: 'A sales representative visited our office.', sort_order: 47 },
  { word: 'inquiry',          word_form: 'noun',          ipa: '/ˈɪŋ.kwɪr.i/',              meaning: 'sự hỏi, yêu cầu thông tin',     example: 'We received an inquiry about pricing.', sort_order: 48 },
  { word: 'general',          word_form: 'adjective',     ipa: '/ˈdʒen.ər.əl/',             meaning: 'chung, tổng quát',               example: 'This email contains general information.', sort_order: 49 },
  { word: 'release',          word_form: 'verb / noun',   ipa: '/rɪˈliːs/',                 meaning: 'phát hành',                      example: 'The company will release the report tomorrow.', sort_order: 50 },
  { word: 'indicate',         word_form: 'verb',          ipa: '/ˈɪn.dɪ.keɪt/',             meaning: 'chỉ ra, cho thấy',               example: 'The survey results indicate high satisfaction.', sort_order: 51 },
  { word: 'retain',           word_form: 'verb',          ipa: '/rɪˈteɪn/',                 meaning: 'giữ lại',                        example: 'The company aims to retain skilled employees.', sort_order: 52 },
  { word: 'flavour',          word_form: 'noun',          ipa: '/ˈfleɪ.vər/',               meaning: 'hương vị',                       example: 'Customers can choose their preferred flavour.', sort_order: 53 },
  { word: 'sacrifice',        word_form: 'verb / noun',   ipa: '/ˈsæk.rɪ.faɪs/',           meaning: 'hy sinh',                        example: 'He sacrificed his time to finish the project.', sort_order: 54 },
  { word: 'obtain',           word_form: 'verb',          ipa: '/əbˈteɪn/',                 meaning: 'đạt được, thu được',             example: 'You must obtain approval before ordering.', sort_order: 55 },
  { word: 'merger',           word_form: 'noun',          ipa: '/ˈmɜːr.dʒər/',              meaning: 'sự sáp nhập',                    example: 'The merger was announced last month.', sort_order: 56 },
  { word: 'nutritious',       word_form: 'adjective',     ipa: '/nuːˈtrɪʃ.əs/',             meaning: 'giàu dinh dưỡng',                example: 'The cafeteria offers nutritious meals.', sort_order: 57 },
  { word: 'individual',       word_form: 'noun / adj',    ipa: '/ˌɪn.dɪˈvɪdʒ.u.əl/',        meaning: 'cá nhân',                        example: 'Each individual employee has a login ID.', sort_order: 58 },
  { word: 'opportunity',      word_form: 'noun',          ipa: '/ˌɑː.pəˈtuː.nə.ti/',        meaning: 'cơ hội',                         example: 'This training is a great opportunity for staff.', sort_order: 59 },
  { word: 'substitute',       word_form: 'verb / noun',   ipa: '/ˈsʌb.stɪ.tuːt/',           meaning: 'thay thế',                       example: 'A temporary worker was hired to substitute her.', sort_order: 60 },
  { word: 'critical',         word_form: 'adjective',     ipa: '/ˈkrɪt.ɪ.kəl/',             meaning: 'mang tính phê bình; quan trọng', example: 'Time management is critical to success.', sort_order: 61 },
  { word: 'colleague',        word_form: 'noun',          ipa: '/ˈkɑː.liːɡ/',               meaning: 'đồng nghiệp',                    example: 'She discussed the issue with her colleagues.', sort_order: 62 },
  { word: 'courtesy',         word_form: 'noun',          ipa: '/ˈkɜː.tə.si/',              meaning: 'lịch sự, nhã nhặn',              example: 'Thank you for your courtesy and support.', sort_order: 63 },
  { word: 'get the word out',  word_form: 'idiom',         ipa: '/ɡet ðə wɜːrd aʊt/',        meaning: 'truyền tin, thông báo rộng rãi', example: 'We used social media to get the word out.', sort_order: 64 },
  { word: 'install',          word_form: 'verb',          ipa: '/ɪnˈstɔːl/',                meaning: 'lắp đặt',                        example: 'The software will be installed this afternoon.', sort_order: 65 },
  { word: 'significant',      word_form: 'adjective',     ipa: '/sɪɡˈnɪf.ɪ.kənt/',          meaning: 'đáng kể, quan trọng',            example: 'There has been a significant increase in sales.', sort_order: 66 },
  { word: 'estimate',         word_form: 'verb / noun',   ipa: '/ˈes.tɪ.meɪt/',             meaning: 'ước tính',                       example: 'The contractor provided a cost estimate.', sort_order: 67 },
  { word: 'liaison',          word_form: 'noun',          ipa: '/lɪˈeɪ.zɑːn/',              meaning: 'người liên lạc',                 example: 'She acts as a liaison between departments.', sort_order: 68 },
  { word: 'successive',       word_form: 'adjective',     ipa: '/səkˈses.ɪv/',              meaning: 'liên tiếp',                      example: 'He arrived late for two successive meetings.', sort_order: 69 },
  { word: 'expert',           word_form: 'noun / adj',    ipa: '/ˈek.spɜːt/',               meaning: 'chuyên gia',                     example: 'Please consult an expert for advice.', sort_order: 70 },
  { word: 'diagnose',         word_form: 'verb',          ipa: '/ˈdaɪ.əɡ.noʊz/',            meaning: 'chẩn đoán',                      example: 'The technician will diagnose the system issue.', sort_order: 71 },
  { word: 'replace',          word_form: 'verb',          ipa: '/rɪˈpleɪs/',                meaning: 'thay thế',                       example: 'The company decided to replace the printer.', sort_order: 72 },
  { word: 'resemble',         word_form: 'verb',          ipa: '/rɪˈzem.bəl/',              meaning: 'giống',                          example: 'The new logo resembles the old design.', sort_order: 73 },
  { word: 'approve',          word_form: 'verb',          ipa: '/əˈpruːv/',                 meaning: 'phê duyệt',                      example: 'The budget was approved by management.', sort_order: 74 },
  { word: 'inspection',       word_form: 'noun',          ipa: '/ɪnˈspek.ʃən/',             meaning: 'kiểm tra',                       example: 'The building passed the safety inspection.', sort_order: 75 },
  { word: 'proactive',        word_form: 'adjective',     ipa: '/proʊˈæk.tɪv/',             meaning: 'chủ động',                       example: 'We encourage proactive communication.', sort_order: 76 },
  { word: 'procedure',        word_form: 'noun',          ipa: '/prəˈsiː.dʒər/',            meaning: 'quy trình',                      example: 'Please follow the standard procedure.', sort_order: 77 },
  { word: 'compete',          word_form: 'verb',          ipa: '/kəmˈpiːt/',                meaning: 'cạnh tranh',                     example: 'Small businesses must compete effectively.', sort_order: 78 },
  { word: 'instrumental',     word_form: 'adjective',     ipa: '/ˌɪn.strəˈmen.təl/',        meaning: 'đóng vai trò quan trọng',        example: 'Her support was instrumental in the project.', sort_order: 79 },
  { word: 'combine',          word_form: 'verb',          ipa: '/kəmˈbaɪn/',                meaning: 'kết hợp',                        example: 'We plan to combine the two departments.', sort_order: 80 },
];

const TEST2: SeedWord[] = [
  { word: 'reliability',   word_form: 'noun',                 ipa: '/rɪˌlaɪ.əˈbɪl.ə.ti/',     meaning: 'sự đáng tin cậy',               example: 'The system is known for its reliability.', sort_order: 1  },
  { word: 'reimbursement', word_form: 'noun',                 ipa: '/ˌriː.ɪmˈbɜːs.mənt/',      meaning: 'sự hoàn tiền',                  example: 'Employees can request travel reimbursement.', sort_order: 2  },
  { word: 'accept',        word_form: 'verb',                 ipa: '/əkˈsept/',                 meaning: 'chấp nhận',                     example: 'She accepted the job offer.', sort_order: 3  },
  { word: 'candidate',     word_form: 'noun',                 ipa: '/ˈkæn.dɪ.deɪt/',           meaning: 'ứng viên',                      example: 'Each candidate was interviewed.', sort_order: 4  },
  { word: 'master',        word_form: 'verb',                 ipa: '/ˈmæs.tər/',                meaning: 'nắm vững, thành thạo',          example: 'He mastered the new software quickly.', sort_order: 5  },
  { word: 'power failure', word_form: 'noun phrase',          ipa: '/ˈpaʊ.ər ˌfeɪl.jər/',      meaning: 'sự mất điện',                   example: 'The meeting was delayed due to a power failure.', sort_order: 6  },
  { word: 'property',      word_form: 'noun',                 ipa: '/ˈprɒː.pər.ti/',            meaning: 'tài sản, bất động sản',         example: 'The company owns several properties downtown.', sort_order: 7  },
  { word: 'strategy',      word_form: 'noun',                 ipa: '/ˈstræt.ə.dʒi/',            meaning: 'chiến lược',                    example: 'Marketing strategy is key to growth.', sort_order: 8  },
  { word: 'name',          word_form: 'verb',                 ipa: '/neɪm/',                    meaning: 'chỉ định, bổ nhiệm',            example: 'She was named team leader.', sort_order: 9  },
  { word: 'warranty',      word_form: 'noun',                 ipa: '/ˈwɒr.ən.ti/',              meaning: 'bảo hành',                      example: 'The product comes with a one-year warranty.', sort_order: 10 },
  { word: 'workplace',     word_form: 'noun',                 ipa: '/ˈwɜːk.pleɪs/',             meaning: 'nơi làm việc',                  example: 'Safety is important in the workplace.', sort_order: 11 },
  { word: 'postpone',      word_form: 'verb',                 ipa: '/poʊstˈpoʊn/',              meaning: 'hoãn lại',                      example: 'The event was postponed until next week.', sort_order: 12 },
  { word: 'struggle',      word_form: 'verb',                 ipa: '/ˈstrʌŋ.əl/',               meaning: 'vật lộn, gặp khó khăn',         example: 'The team struggled to meet the deadline.', sort_order: 13 },
  { word: 'ingredient',    word_form: 'noun',                 ipa: '/ɪnˈɡriː.di.ənt/',          meaning: 'thành phần',                    example: 'Fresh ingredients are used in the cafeteria.', sort_order: 14 },
  { word: 'savory',        word_form: 'adjective',            ipa: '/ˈseɪ.vər.i/',              meaning: 'mặn, đậm vị',                   example: 'The restaurant offers savory lunch options.', sort_order: 15 },
  { word: 'eager',         word_form: 'adjective',            ipa: '/ˈiː.ɡər/',                 meaning: 'háo hức, mong muốn',            example: 'She is eager to learn new skills.', sort_order: 16 },
  { word: 'artificial',    word_form: 'adjective',            ipa: '/ˌɑːr.tɪˈfɪʃ.əl/',         meaning: 'nhân tạo',                      example: 'The room uses artificial lighting.', sort_order: 17 },
  { word: 'substance',     word_form: 'noun',                 ipa: '/ˈsʌb.stəns/',              meaning: 'chất, vật chất',                example: 'The report lacks useful substance.', sort_order: 18 },
  { word: 'handy',         word_form: 'adjective',            ipa: '/ˈhæn.di/',                 meaning: 'tiện lợi',                      example: 'This app is very handy for work.', sort_order: 19 },
  { word: 'effective',     word_form: 'adjective',            ipa: '/ɪˈfek.tɪv/',               meaning: 'hiệu quả',                      example: 'The new system is more effective.', sort_order: 20 },
  { word: 'sustainable',   word_form: 'adjective',            ipa: '/səˈsteɪ.nə.bl/',           meaning: 'bền vững',                      example: 'The company aims for sustainable growth.', sort_order: 21 },
  { word: 'address',       word_form: 'verb',                 ipa: '/əˈdrɛs/',                  meaning: 'giải quyết',                    example: 'We need to address customer complaints quickly.', sort_order: 22 },
  { word: 'porous',        word_form: 'adjective',            ipa: '/ˈpɔːr.əs/',                meaning: 'xốp, thấm nước',                example: 'This material is too porous for outdoor use.', sort_order: 23 },
  { word: 'subscription',  word_form: 'noun',                 ipa: '/səbˈskrɪp.ʃən/',           meaning: 'sự đăng ký, thuê bao',          example: 'She bought a one-year magazine subscription.', sort_order: 24 },
  { word: 'access',        word_form: 'noun / verb',          ipa: '/ˈæk.ses/',                 meaning: 'quyền truy cập / truy cập',     example: 'Employees can access the system online.', sort_order: 25 },
  { word: 'valid',         word_form: 'adjective',            ipa: '/ˈvæl.ɪd/',                 meaning: 'hợp lệ, còn hiệu lực',          example: 'Your ticket is valid until Friday.', sort_order: 26 },
  { word: 'expire',        word_form: 'verb',                 ipa: '/ɪkˈspaɪər/',               meaning: 'hết hạn',                       example: 'The contract will expire next month.', sort_order: 27 },
  { word: 'activate',      word_form: 'verb',                 ipa: '/ˈæk.tɪ.veɪt/',             meaning: 'kích hoạt',                     example: 'Please activate your card before use.', sort_order: 28 },
  { word: 'distribute',    word_form: 'verb',                 ipa: '/dɪˈstrɪb.juːt/',           meaning: 'phân phối',                     example: 'The company distributes products nationwide.', sort_order: 29 },
  { word: 'feature',       word_form: 'noun / verb',          ipa: '/ˈfiː.tʃər/',               meaning: 'tính năng / có đặc điểm',       example: 'This phone features a large screen.', sort_order: 30 },
  { word: 'reveal',        word_form: 'verb',                 ipa: '/rɪˈviːl/',                 meaning: 'tiết lộ',                       example: 'The report revealed a drop in sales.', sort_order: 31 },
  { word: 'extension',     word_form: 'noun',                 ipa: '/ɪkˈsten.ʃən/',             meaning: 'sự gia hạn, số máy lẻ',         example: 'He asked for an extension of the deadline.', sort_order: 32 },
  { word: 'complaint',     word_form: 'noun',                 ipa: '/kəmˈpleɪnt/',              meaning: 'lời phàn nàn',                  example: 'We received a complaint from a customer.', sort_order: 33 },
  { word: 'issue',         word_form: 'noun / verb',          ipa: '/ˈɪʃ.uː/',                  meaning: 'vấn đề / phát hành',            example: 'This is a serious safety issue.', sort_order: 34 },
  { word: 'maintenance',   word_form: 'noun',                 ipa: '/ˈmeɪn.tən.əns/',           meaning: 'bảo trì',                       example: 'The machine needs regular maintenance.', sort_order: 35 },
  { word: 'summarize',     word_form: 'verb',                 ipa: '/ˈsʌm.ər.aɪz/',             meaning: 'tóm tắt',                       example: 'Please summarize the meeting notes.', sort_order: 36 },
  { word: 'notify',        word_form: 'verb',                 ipa: '/ˈnoʊ.tɪ.faɪ/',             meaning: 'thông báo',                     example: 'We will notify you by email.', sort_order: 37 },
  { word: 'requirement',   word_form: 'noun',                 ipa: '/rɪˈkwaɪər.mənt/',          meaning: 'yêu cầu, điều kiện',            example: 'Experience is a job requirement.', sort_order: 38 },
  { word: 'freight',       word_form: 'noun',                 ipa: '/freɪt/',                   meaning: 'hàng hóa vận chuyển',           example: 'Freight costs have increased this year.', sort_order: 39 },
  { word: 'vehicle',       word_form: 'noun',                 ipa: '/ˈviː.ə.kl/',               meaning: 'phương tiện, xe cộ',            example: 'Company vehicles are parked outside.', sort_order: 40 },
  { word: 'transport',     word_form: 'verb / noun',          ipa: '/ˈtræns.pɔːrt/',            meaning: 'vận chuyển / sự vận chuyển',    example: 'The goods are transported by truck.', sort_order: 41 },
  { word: 'nationwide',    word_form: 'adverb / adjective',   ipa: '/ˌneɪ.ʃənˈwaɪd/',           meaning: 'trên toàn quốc',                example: 'The service is available nationwide.', sort_order: 42 },
  { word: 'executive',     word_form: 'noun / adjective',     ipa: '/ɪɡˈzek.jə.tɪv/',           meaning: 'giám đốc, lãnh đạo / điều hành', example: 'The executive discussed company strategy.', sort_order: 43 },
  { word: 'commercial',    word_form: 'adjective',            ipa: '/kəˈmɜːr.ʃəl/',             meaning: 'thương mại',                    example: 'This is a commercial building.', sort_order: 44 },
  { word: 'demand',        word_form: 'noun / verb',          ipa: '/dɪˈmɑːnd/',                meaning: 'nhu cầu / yêu cầu',             example: 'There is high demand for this product.', sort_order: 45 },
  { word: 'specialty',     word_form: 'noun',                 ipa: '/ˈspeʃ.əl.ti/',             meaning: 'chuyên môn, lĩnh vực đặc biệt', example: 'Marketing is her specialty.', sort_order: 46 },
  { word: 'convert',       word_form: 'verb',                 ipa: '/kənˈvɜːrt/',               meaning: 'chuyển đổi',                    example: 'They converted the office into a meeting room.', sort_order: 47 },
  { word: 'virtual',       word_form: 'adjective',            ipa: '/ˈvɜːr.tʃu.əl/',            meaning: 'ảo, trực tuyến',                example: 'The team held a virtual meeting.', sort_order: 48 },
  { word: 'visualization', word_form: 'noun',                 ipa: '/ˌvɪʒ.u.ə.laɪˈzeɪ.ʃən/',   meaning: 'sự trực quan hóa',              example: 'Data visualization helps explain results.', sort_order: 49 },
  { word: 'suggest',       word_form: 'verb',                 ipa: '/səˈdʒest/',                meaning: 'đề xuất',                       example: 'I suggest starting the project early.', sort_order: 50 },
  { word: 'curate',        word_form: 'verb',                 ipa: '/kjuˈreɪt/',                meaning: 'tuyển chọn, chọn lọc',          example: 'She curates content for the website.', sort_order: 51 },
  { word: 'highlight',     word_form: 'verb / noun',          ipa: '/ˈhaɪ.laɪt/',               meaning: 'làm nổi bật / điểm nổi bật',   example: 'The report highlights key problems.', sort_order: 52 },
  { word: 'process',       word_form: 'verb / noun',          ipa: '/ˈproʊ.ses/',               meaning: 'xử lý / quy trình',             example: 'We process orders within 24 hours.', sort_order: 53 },
];

export const SEED_SETS: SeedSet[] = [
  { set_name: 'ETS_2026_TEST1', words: TEST1 },
  { set_name: 'ETS_2026_TEST2', words: TEST2 },
];
